name: Test Coverage

on:
  push:
  pull_request:

env:
  CI: true
  node-version: lts/*

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        name: Node ${{ env.node-version }}
        with:
          node-version: ${{ env.node-version }}

      - uses: actions/checkout@v4

      - run: npm install

      - name: run coverage
        run: npx -y c8 --reporter=lcov npm test
        env:
          NODE_ENV: cov

      - name: codecov
        uses: codecov/codecov-action@v2

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
